import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>
        <button className="btn btn-active">Button</button>
        <button className="btn btn-active btn-primary">Button</button>
        <button className="btn btn-active btn-secondary">Button</button>
        <button className="btn btn-active btn-accent">Button</button>
        <button className="btn btn-active btn-ghost">Button</button>
        <button className="btn btn-active btn-link">Button</button>
      </main>
    </>
  )
}
